import "@/styles/global.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import MarginWidthWrapper from "@/components/margin-width-wrapper";
import PageWrapper from "@/components/page-wrapper";
import ClientLayout from "@/components/clientLayout";

import { Providers } from "./providers";
import { ClerkProvider } from "@clerk/nextjs";

import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Side Nav w/ submenus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <Providers>
            <ClientLayout>
              <MarginWidthWrapper>
                <PageWrapper>
                  {children}
                  <SpeedInsights />
                </PageWrapper>
              </MarginWidthWrapper>
            </ClientLayout>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
